package com.webservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2015-11-29T23:59:55.679+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://ws.webservice.com/", name = "SayHelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface SayHelloWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.webservice.com/", className = "com.webservice.ws.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.webservice.com/", className = "com.webservice.ws.SayHelloResponse")
    public java.lang.String sayHello();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudentById", targetNamespace = "http://ws.webservice.com/", className = "com.webservice.ws.GetStudentById")
    @WebMethod
    @ResponseWrapper(localName = "getStudentByIdResponse", targetNamespace = "http://ws.webservice.com/", className = "com.webservice.ws.GetStudentByIdResponse")
    public com.webservice.ws.Student getStudentById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "yinrongSayHello", targetNamespace = "http://ws.webservice.com/", className = "com.webservice.ws.YinrongSayHello")
    @WebMethod
    @ResponseWrapper(localName = "yinrongSayHelloResponse", targetNamespace = "http://ws.webservice.com/", className = "com.webservice.ws.YinrongSayHelloResponse")
    public java.lang.String yinrongSayHello(
        @WebParam(name = "onename", targetNamespace = "")
        java.lang.String onename
    );
}
